version: 2.1
jobs:
  frontend_lint:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/pct-homework-helper
    steps:
      - checkout
      - run:
          command: |
            npm install
            npm run lint
  # backend_test:
  #   docker:
  #     - image: circleci/node:10.16.3
  #   working_directory: ~/pct-homework-helper
  #   steps:
  #     - checkout
  #     - run:
  #         command: |
  #           cd api
  #           npm install
  #           npm test
  # backend_lint:
  #   docker:
  #     - image: circleci/node:10.16.3
  #   working_directory: ~/pct-homework-helper
  #   steps:
  #     - checkout
  #     - run:
  #         command: |
  #           cd api
  #           npm install
  #           npm lint
  # auth_test:
  #   docker:
  #     - image: node:11.14.0
  #   working_directory: ~/pct-homework-helper
  #   dependencies:
  #     override:
  #       - echo $PATH
  #   steps:
  #     - checkout
  #     - run:
  #         command: |
  #           cd auth
  #           npm install
  #           npm test
workflows:
  version: 2.1
  build_test:
    jobs:
      - frontend_lint
